# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 08:12
from __future__ import unicode_literals

import descriptors.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=descriptors.models.upload_thumbnail_location)),
                ('width', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('isPrivate', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
                ('fork', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptor', to='assets.Asset')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset', to='categories.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset', to='categories.SubCategory')),
            ],
        ),
    ]
