# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='descriptor',
            name='subcategory',
        ),
    ]
