# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset', to='categories.SubCategory'),
            preserve_default=False,
        ),
    ]
